### ISSUE TITLE
npm install $ not work

### ISSUE THREAD

**Issue by 82318179** [fabiospampinato/cash#421] opened 2023-04-30 13:37 UTC
import $, { Cash } from 'cash-dom';
class Test {
  constructor() {
    let a = $('body')[0]; //undefined
    let b = document.querySelectorAll('body')[0]; //OK
  }
}

When used  $  in the constructor of a class, it is found that the return is undefined, but using pure JavaScript can indeed obtain data.
How to fix this problem?

**Comment by fabiospampinato** [comment] 2023-05-22 15:36
I can't reproduce the problem with the following code:

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <script type="module">
    import $, { Cash } from 'https://esm.sh/cash-dom';
    class Test {
      constructor() {
        let a = $('body')[0]; //undefined
        let b = document.querySelectorAll('body')[0]; //OK
        console.log ({ a, b });
      }
    }
    new Test ();
  </script>
</body>
</html>
```

I'm closing as this sounds like a non-issue with the library probably? Maybe some issue with your bundling setup or something?

Happy to reopen if you can provide a reproduction of the problem.

**Closed by fabiospampinato** 2023-05-22 15:36 UTC
