### ISSUE TITLE
Cannot set property length of #<NodeList> which has only a getter

### ISSUE THREAD

**Issue by Stumblor** [fabiospampinato/cash#364] opened 2021-02-23 13:23 UTC
Getting this error whenever trying to execute a child method on an existing selected object.

For example

$('body').find('input');

**Comment by fabiospampinato** [comment] 2021-04-01 18:57
I can't reproduce the issue, can you make a repro?

**Comment by fabiospampinato** [comment] 2021-04-02 15:31
Closing, feel free to reopen or comment once you have a way to reproduce the issue, most probably you are using cash properly somehow, like maybe `$` doesn't even point to cash.

**Closed by fabiospampinato** 2021-04-02 15:31 UTC
Labels: needs more info

**Comment by saurookadook** [comment] 2021-04-27 19:40
@fabiospampinato I ran into something similar recently, though it was in reference to an `Event` object.

I was trying to alter the Slick library in such a way so that it could be used with `cash` (and, by extension, still be used with jQuery), but I came across an identical error when trying to directly set `data` on an `Event`:
https://github.com/amaskiellEG/slick/pull/1/files#diff-2f5452c5fb614ae996479ebab3a358c801289d34cf343d5438545332c1f1639eR656-R661
```js
Slick.prototype.changeSlide = function(event, dontAnimate) {

        if (!(event instanceof Event)) {
            var eventData = event;
            event = arguments[1];
            event.data = eventData;
        }
```

I found a way to get around it for now, but it wasn't great:
```js
Slick.prototype.changeSlide = function(event, dontAnimate) {
        var eventData;

        if (event.data) {
            eventData = event.data;
        } else if (!(event instanceof Event)) {
            eventData = event;
            event = arguments[1];
            if (event.data) Object.assign(eventData, event.data);
        }
```

I _did_ just noticed that jQuery is still being loaded on the page, but based on how slick seems to initialize everything, I don't _think_ that would be the cause?
